# Generated by Django 4.2.7 on 2023-12-06 11:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Venue', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('notes', models.TextField(max_length=1000)),
                ('starting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Origin', models.CharField(default='WEB', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snumber', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='Teachingapp.tag')),
                ('views', models.ManyToManyField(blank=True, related_name='views', to='Teachingapp.user')),
            ],
        ),
    ]
