# Generated by Django 4.2.7 on 2023-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachingapp', '0003_remove_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='views',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Teachingapp.tag'),
        ),
    ]
