# Generated by Django 4.2.7 on 2023-12-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachingapp', '0004_remove_event_views_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
