# Generated by Django 4.2.7 on 2023-12-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachingapp', '0007_alter_event_starting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='snumber',
        ),
    ]
